name: Update data

on:  
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
#    inputs:        
#      logLevel:
#        description: 'Log level'
#        required: true
#        default: 'warning'
#        type: choice
#        options:
#        - info
#        - warning
#        - debug
#      tags:
#        description: 'Test scenario tags'
#        required: false
#        type: boolean
    
jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Run Node.js
        run: node --experimental-fetch update.js
        
      - name: Commit new files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          timeout_seconds: 15
          max_attempts: 3
          continue_on_error: true
          commit_message: (BOT) Update data
          
          
      - name: Run Node.js
        run: node --experimental-fetch update.js
        
      - name: Commit new files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          timeout_seconds: 15
          max_attempts: 3
          continue_on_error: true
          commit_message: (BOT) Update data
          
          
      - name: Run Node.js
        run: node --experimental-fetch update.js
        
      - name: Commit new files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          timeout_seconds: 15
          max_attempts: 3
          continue_on_error: true
          commit_message: (BOT) Update data
          
          
      - name: Run Node.js
        run: node --experimental-fetch update.js
        
      - name: Commit new files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          timeout_seconds: 15
          max_attempts: 3
          continue_on_error: true
          commit_message: (BOT) Update data
          
          
      - name: Run Node.js
        run: node --experimental-fetch update.js
        
      - name: Commit new files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          timeout_seconds: 15
          max_attempts: 3
          continue_on_error: true
          commit_message: (BOT) Update data
          
          
      - name: Run Node.js
        run: node --experimental-fetch update.js
        
      - name: Commit new files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          timeout_seconds: 15
          max_attempts: 3
          continue_on_error: true
          commit_message: (BOT) Update data
          
          
      - name: Run Node.js
        run: node --experimental-fetch update.js
        
      - name: Commit new files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          timeout_seconds: 15
          max_attempts: 3
          continue_on_error: true
          commit_message: (BOT) Update data
          
          
      - name: Run Node.js
        run: node --experimental-fetch update.js
        
      - name: Commit new files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          timeout_seconds: 15
          max_attempts: 3
          continue_on_error: true
          commit_message: (BOT) Update data
          
          
      - name: Run Node.js
        run: node --experimental-fetch update.js
        
      - name: Commit new files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          timeout_seconds: 15
          max_attempts: 3
          continue_on_error: true
          commit_message: (BOT) Update data
          
          
      - name: Run Node.js
        run: node --experimental-fetch update.js
        
      - name: Commit new files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          timeout_seconds: 15
          max_attempts: 3
          continue_on_error: true
          commit_message: (BOT) Update data
          
          
      - name: Run Node.js
        run: node --experimental-fetch update.js
        
      - name: Commit new files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          timeout_seconds: 15
          max_attempts: 3
          continue_on_error: true
          commit_message: (BOT) Update data
          
          
      - name: Run Node.js
        run: node --experimental-fetch update.js
        
      - name: Commit new files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          timeout_seconds: 15
          max_attempts: 3
          continue_on_error: true
          commit_message: (BOT) Update data
          
          
      - name: Run Node.js
        run: node --experimental-fetch update.js
        
      - name: Commit new files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          timeout_seconds: 15
          max_attempts: 3
          continue_on_error: true
          commit_message: (BOT) Update data
          
          
      - name: Run Node.js
        run: node --experimental-fetch update.js
        
      - name: Commit new files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          timeout_seconds: 15
          max_attempts: 3
          continue_on_error: true
          commit_message: (BOT) Update data
          
          
      - name: Run Node.js
        run: node --experimental-fetch update.js
        
      - name: Commit new files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          timeout_seconds: 15
          max_attempts: 3
          continue_on_error: true
          commit_message: (BOT) Update data
          
          
      - name: Run Node.js
        run: node --experimental-fetch update.js
        
      - name: Commit new files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          timeout_seconds: 15
          max_attempts: 3
          continue_on_error: true
          commit_message: (BOT) Update data
          
          
      - name: Run Node.js
        run: node --experimental-fetch update.js
        
      - name: Commit new files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          timeout_seconds: 15
          max_attempts: 3
          continue_on_error: true
          commit_message: (BOT) Update data
          
          
      - name: Run Node.js
        run: node --experimental-fetch update.js
        
      - name: Commit new files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          timeout_seconds: 15
          max_attempts: 3
          continue_on_error: true
          commit_message: (BOT) Update data
          
          
      - name: Run Node.js
        run: node --experimental-fetch update.js
        
      - name: Commit new files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          timeout_seconds: 15
          max_attempts: 3
          continue_on_error: true
          commit_message: (BOT) Update data
          
          
      - name: Run Node.js
        run: node --experimental-fetch update.js
        
      - name: Commit new files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          timeout_seconds: 15
          max_attempts: 3
          continue_on_error: true
          commit_message: (BOT) Update data
          
          
      - name: Run Node.js
        run: node --experimental-fetch update.js
        
      - name: Commit new files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          timeout_seconds: 15
          max_attempts: 3
          continue_on_error: true
          commit_message: (BOT) Update data
          
          
      - name: Run Node.js
        run: node --experimental-fetch update.js
        
      - name: Commit new files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          timeout_seconds: 15
          max_attempts: 3
          continue_on_error: true
          commit_message: (BOT) Update data
          
          
      - name: Run Node.js
        run: node --experimental-fetch update.js
        
      - name: Commit new files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          timeout_seconds: 15
          max_attempts: 3
          continue_on_error: true
          commit_message: (BOT) Update data
          
          
      - name: Run Node.js
        run: node --experimental-fetch update.js
        
      - name: Commit new files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          timeout_seconds: 15
          max_attempts: 3
          continue_on_error: true
          commit_message: (BOT) Update data
          
          
      - name: Run Node.js
        run: node --experimental-fetch update.js
        
      - name: Commit new files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          timeout_seconds: 15
          max_attempts: 3
          continue_on_error: true
          commit_message: (BOT) Update data
          
          
      - name: Run Node.js
        run: node --experimental-fetch update.js
        
      - name: Commit new files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          timeout_seconds: 15
          max_attempts: 3
          continue_on_error: true
          commit_message: (BOT) Update data
          
          
      - name: Run Node.js
        run: node --experimental-fetch update.js
        
      - name: Commit new files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          timeout_seconds: 15
          max_attempts: 3
          continue_on_error: true
          commit_message: (BOT) Update data
